name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      DOCKER_REGISTRY_URL: 'http://10.75.12.85:8085'
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: 'http://10.75.12.85:9000'

    steps:
    - name: Unset Proxy Variables
      run: |
        unset http_proxy
        unset https_proxy
        unset HTTP_PROXY
        unset HTTPS_PROXY

    - name: Checkout Source Code
      uses: actions/checkout@v2
      with:
        repository: 'Vidyashree-tata/java_springboot'
        ref: 'develop'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Update DNS Settings
      run: |
        echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
        echo "nameserver 1.1.1.1" | sudo tee -a /etc/resolv.conf

    # Commenting out Docker Nexus Login step
    # - name: Docker Nexus Login
    #   uses: docker/login-action@v2
    #   with:
    #     registry: http://10.75.12.85:8085
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build and Push
      run: |
        docker build -t trans_planner:1.0 .
        docker tag trans_planner:1.0 10.75.12.85:8085/trans_planner:1.0
        docker push 10.75.12.85:8085/trans_planner:1.0

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f trans_planner_deployment.yaml
        kubectl get pods -n transconnect
        kubectl get svc -n transconnect
